(part "B3U-3100P-B"
    (packageRef "B3U-3100P-B")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "OMRON Electronics")
    (property "Manufacturer_Part_Number" "B3U-3100P-B")
    (property "Mouser_Part_Number" "653-B3U-3100P-B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/B3U-3100P-B?qs=q8ECNkb1%2FvNLWRjRd0Yozg%3D%3D")
    (property "Arrow_Part_Number" "B3U-3100P-B")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/b3u-3100p-b/omron?utm_currency=USD&region=nac")
    (property "Description" "Ultra-small Tactile Switch (SMT), With Boss, With Ground Terminal, Height 3.2mm, OF:1.59N")
    (property "Datasheet_Link" "https://components.omron.com/us-en/sites/components.omron.com.us/files/datasheet_pdf/A162-E1.pdf")
    (property "symbolName1" "B3U-3100P-B")
)
