(part "BAT54KFILM"
    (packageRef "SODFL1608X70N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "BAT54KFILM")
    (property "Mouser_Part_Number" "511-BAT54KFILM")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/BAT54KFILM?qs=jZi1jxfVU95Y9ce6l3OT%252BA%3D%3D")
    (property "Arrow_Part_Number" "BAT54KFILM")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/bat54kfilm/stmicroelectronics?region=europe")
    (property "Description" "BAT54KFILM, Schottky Diode,  0.3A max, 40V 5ns, 2-Pin, SOD-523")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/bat54.pdf")
    (property "symbolName1" "BAT54KFILM")
)
