PULSONIX_LIBRARY_ASCII "SamacSys ECAD Model"
//179122/353529/2.50/2/2/Diode

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "r70_42"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 0.42) (shapeHeight 0.7))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(textStyleDef "Normal"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 1.27)
			(strokeWidth 0.127)
		)
	)
	(patternDef "SODFL1608X70N" (originalName "SODFL1608X70N")
		(multiLayer
			(pad (padNum 1) (padStyleRef r70_42) (pt -0.725, 0) (rotation 90))
			(pad (padNum 2) (padStyleRef r70_42) (pt 0.725, 0) (rotation 90))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt 0, 0) (textStyleRef "Normal") (isVisible True))
		)
		(layerContents (layerNumRef Courtyard_Top)
			(line (pt -1.225 0.6) (pt 1.225 0.6) (width 0.05))
		)
		(layerContents (layerNumRef Courtyard_Top)
			(line (pt 1.225 0.6) (pt 1.225 -0.6) (width 0.05))
		)
		(layerContents (layerNumRef Courtyard_Top)
			(line (pt 1.225 -0.6) (pt -1.225 -0.6) (width 0.05))
		)
		(layerContents (layerNumRef Courtyard_Top)
			(line (pt -1.225 -0.6) (pt -1.225 0.6) (width 0.05))
		)
		(layerContents (layerNumRef 28)
			(line (pt -0.6 0.4) (pt 0.6 0.4) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt 0.6 0.4) (pt 0.6 -0.4) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt 0.6 -0.4) (pt -0.6 -0.4) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt -0.6 -0.4) (pt -0.6 0.4) (width 0.025))
		)
		(layerContents (layerNumRef 28)
			(line (pt -0.6 0.05) (pt -0.25 0.4) (width 0.025))
		)
		(layerContents (layerNumRef 18)
			(line (pt -1.075 0.4) (pt 0.6 0.4) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt -0.6 -0.4) (pt 0.6 -0.4) (width 0.2))
		)
	)
	(symbolDef "BAT54KFILM" (originalName "BAT54KFILM")

		(pin (pinNum 1) (pt 0 mils 0 mils) (rotation 0) (pinLength 100 mils) (pinDisplay (dispPinName false)) (pinName (text (pt 140 mils -15 mils) (rotation 0]) (justify "Left") (textStyleRef "Normal"))
		))
		(pin (pinNum 2) (pt 600 mils 0 mils) (rotation 180) (pinLength 100 mils) (pinDisplay (dispPinName false)) (pinName (text (pt 460 mils -15 mils) (rotation 0]) (justify "Right") (textStyleRef "Normal"))
		))
		(line (pt 200 mils 100 mils) (pt 200 mils -100 mils) (width 6 mils))
		(line (pt 100 mils 0 mils) (pt 200 mils 0 mils) (width 6 mils))
		(line (pt 400 mils 0 mils) (pt 500 mils 0 mils) (width 6 mils))
		(poly (pt 200 mils 0 mils) (pt 400 mils 100 mils) (pt 400 mils -100 mils) (pt 200 mils 0 mils) (width 10  mils))
		(attr "RefDes" "RefDes" (pt 450 mils 200 mils) (justify Left) (isVisible True) (textStyleRef "Normal"))
		(attr "Type" "Type" (pt 450 mils 100 mils) (justify Left) (isVisible True) (textStyleRef "Normal"))

	)
	(compDef "BAT54KFILM" (originalName "BAT54KFILM") (compHeader (numPins 2) (numParts 1) (refDesPrefix D)
		)
		(compPin "1" (pinName "K") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Unknown))
		(compPin "2" (pinName "A") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Unknown))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "BAT54KFILM"))
		(attachedPattern (patternNum 1) (patternName "SODFL1608X70N")
			(numPads 2)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
			)
		)
		(attr "Manufacturer_Name" "STMicroelectronics")
		(attr "Manufacturer_Part_Number" "BAT54KFILM")
		(attr "Mouser Part Number" "511-BAT54KFILM")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/BAT54KFILM?qs=jZi1jxfVU95Y9ce6l3OT%252BA%3D%3D")
		(attr "Arrow Part Number" "BAT54KFILM")
		(attr "Arrow Price/Stock" "https://www.arrow.com/en/products/bat54kfilm/stmicroelectronics?region=europe")
		(attr "Description" "BAT54KFILM, Schottky Diode,  0.3A max, 40V 5ns, 2-Pin, SOD-523")
		(attr "<Hyperlink>" "https://www.st.com/resource/en/datasheet/bat54.pdf")
		(attr "<Component Height>" "0.7")
		(attr "<STEP Filename>" "BAT54KFILM.stp")
		(attr "<STEP Offsets>" "X=0;Y=0;Z=0")
		(attr "<STEP Rotation>" "X=0;Y=0;Z=0")
	)

)
