(part "B3U-3000P-B"
    (packageRef "B3U3000PB")
    (interface
        (port "1" (symbPinId 1) (portName "COM") (portType INOUT))
        (port "2" (symbPinId 2) (portName "N.O.") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "OMRON Electronics")
    (property "Manufacturer_Part_Number" "B3U-3000P-B")
    (property "Mouser_Part_Number" "653-B3U-3000P-B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/B3U-3000P-B?qs=AO7BQMcsEu4JAdtnbsGArA%3D%3D")
    (property "Arrow_Part_Number" "B3U-3000P-B")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/b3u-3000p-b/omron?utm_currency=USD&region=nac")
    (property "Description" "OMRON - B3U-3000P-B - TACTILE SWITCH, SIDE ACTUATED, SMD")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/B3U-3000P-B.pdf")
    (property "symbolName1" "B3U-3000P-B")
)
