(part "AS5047P-ATSM"
    (packageRef "SOP65P640X120-14N")
    (interface
        (port "1" (symbPinId 1) (portName "CSN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CLK") (portType INOUT))
        (port "3" (symbPinId 3) (portName "MISO") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MOSI") (portType INOUT))
        (port "5" (symbPinId 5) (portName "TEST") (portType INOUT))
        (port "6" (symbPinId 6) (portName "B") (portType INOUT))
        (port "7" (symbPinId 7) (portName "A") (portType INOUT))
        (port "8" (symbPinId 8) (portName "W/PWM") (portType INOUT))
        (port "9" (symbPinId 9) (portName "V") (portType INOUT))
        (port "10" (symbPinId 10) (portName "U") (portType INOUT))
        (port "11" (symbPinId 11) (portName "VDD") (portType INOUT))
        (port "12" (symbPinId 12) (portName "VDD3V") (portType INOUT))
        (port "13" (symbPinId 13) (portName "GND") (portType INOUT))
        (port "14" (symbPinId 14) (portName "I/PWM") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "985-AS5047P-ATSM")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ams-OSRAM/AS5047P-ATSM?qs=cGEy3R83DS8fzNOVLHtOgg%3D%3D")
    (property "Manufacturer_Name" "ams OSRAM")
    (property "Manufacturer_Part_Number" "AS5047P-ATSM")
    (property "Description" "Board Mount Hall Effect / Magnetic Sensors 14 bit core res Up to 28krpm")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/DKDS-7/120640.pdf")
    (property "symbolName1" "AS5047P-ATSM")
)
