(part "TMC6300-LA"
    (packageRef "QFN40P300X300X90-21N")
    (interface
        (port "1" (symbPinId 1) (portName "W") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VCP") (portType INOUT))
        (port "3" (symbPinId 3) (portName "UH") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VH") (portType INOUT))
        (port "5" (symbPinId 5) (portName "WH") (portType INOUT))
        (port "6" (symbPinId 6) (portName "UL") (portType INOUT))
        (port "7" (symbPinId 7) (portName "WL") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND_1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GND_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VL") (portType INOUT))
        (port "11" (symbPinId 11) (portName "VIO/NSTDBY") (portType INOUT))
        (port "12" (symbPinId 12) (portName "DIAG") (portType INOUT))
        (port "13" (symbPinId 13) (portName "1.8VOUT") (portType INOUT))
        (port "14" (symbPinId 14) (portName "GND_3") (portType INOUT))
        (port "15" (symbPinId 15) (portName "U") (portType INOUT))
        (port "16" (symbPinId 16) (portName "BRUV") (portType INOUT))
        (port "17" (symbPinId 17) (portName "V") (portType INOUT))
        (port "18" (symbPinId 18) (portName "VS") (portType INOUT))
        (port "19" (symbPinId 19) (portName "N.C.") (portType INOUT))
        (port "20" (symbPinId 20) (portName "BRW") (portType INOUT))
        (port "21" (symbPinId 21) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "TMC6300-LA")
    (property "Mouser_Part_Number" "700-TMC6300-LA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ADI-Trinamic/TMC6300-LA?qs=QNEnbhJQKvYIagO3WUG%252BYg%3D%3D")
    (property "Arrow_Part_Number" "TMC6300-LA")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tmc6300-la/analog-devices?region=nac")
    (property "Description" "Highly Efficient Low Voltage, Zero Standby Current Driver for 3-Phase BLDC/PMSM Motors up to 2A peak, Triple Half-Bridge with separate HS and LS control signals")
    (property "Datasheet_Link" "https://www.analog.com/TMC6300/datasheet")
    (property "symbolName1" "TMC6300-LA")
)
