(part "TCPP01-M12"
    (packageRef "QFN50P300X300X100-13N-D")
    (interface
        (port "1" (symbPinId 1) (portName "CC2") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CC1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SOURCE") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GATE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VBUS_CTRL") (portType INOUT))
        (port "7" (symbPinId 7) (portName "CC1C") (portType INOUT))
        (port "8" (symbPinId 8) (portName "IN_GD") (portType INOUT))
        (port "9" (symbPinId 9) (portName "CC2C") (portType INOUT))
        (port "10" (symbPinId 10) (portName "DB/") (portType INOUT))
        (port "11" (symbPinId 11) (portName "FLT/") (portType INOUT))
        (port "12" (symbPinId 12) (portName "VCC") (portType INOUT))
        (port "13" (symbPinId 13) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "TCPP01-M12")
    (property "Mouser_Part_Number" "511-TCPP01-M12")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/TCPP01-M12?qs=%252B6g0mu59x7KCafIwapwG2A%3D%3D")
    (property "Arrow_Part_Number" "TCPP01-M12")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tcpp01-m12/stmicroelectronics.html?utm_currency=USD&region=europe")
    (property "Description" "USB Type-C and power delivery protection for sink application")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/tcpp01-m12.pdf")
    (property "symbolName1" "TCPP01-M12")
)
