(part "BAS70KFILM"
    (packageRef "SODFL1608X70N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "BAS70KFILM")
    (property "Mouser_Part_Number" "511-BAS70KFILM")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/BAS70KFILM?qs=jZi1jxfVU95GtldeDT2NyQ%3D%3D")
    (property "Arrow_Part_Number" "BAS70KFILM")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/bas70kfilm/stmicroelectronics?region=nac")
    (property "Description" "STMicroelectronics BAS70KFILM, SMT Schottky Diode, 70V 70mA, 2-Pin SOD-523")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/bas70.pdf")
    (property "symbolName1" "BAS70KFILM")
)
